services:
  - type: web
    name: yaws
    env: python
    region: oregon # Choose your preferred region
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn.conf.py 'app:create_app("production")'
    autoDeploy: false
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.0
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      # Database configuration - these values need to be set in Render dashboard
      - key: DATABASE_URL
        sync: false
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
    healthCheckPath: /
    # Add minimal instance size
    initialDeployHook: flask db upgrade # Run migrations on deploy
    disk:
      name: uploads
      mountPath: /app/app/uploads
      sizeGB: 1
